services:
  - type: web # This might be 'web' for you
    name: my-telegram-bot
    env: python
    startCommand: "gunicorn app:app & python3 bot.py"
    instances: 1  # <-- THIS IS THE FIX. MAKE SURE IT IS 1.
